Repository marcosdosea/AgendeMe, pull requests merged in 2022-11, with the labels that each got.

#336 Criada tela 12_01 do caso de uso Manter Cargo.
  Codigo/AgendeMeWeb/Models/CargoViewModel.cs
  Codigo/AgendeMeWeb/Views/Cargo/Create.cshtml
Labels: code, 5.0

#340 Corrigindo margin e tamanho do botão de cadastro na tela XL
  Codigo/AgendeMeWeb/Views/Cargo/Create.cshtml
Labels: repair, code, 5.0

#338 Tela 12_02 personalizada de acordo com protótipo.
  Codigo/AgendeMeWeb/Views/Cargo/Edit.cshtml
Labels: code, 5.0

#343 Implementado testes para a controller AgendarServico
  Codigo/AgendeMeWebTests/Controllers/AgendarServicoControllerTests.cs
Labels: test module, 5.0

#344 classe ServicoPublicoServiceTests
  Codigo/ServiceTests/ServicoPublicoServiceTests.cs
Labels: 5.0

#345 Implementação da tela 01_02
  AnaliseProjeto/AgendeMe.mwb
  AnaliseProjeto/AgendeMe.mwb.bak
  Codigo/AgendeMeWeb/Models/CidadaoViewModel.cs
  Codigo/AgendeMeWeb/Views/Cidadao/Create.cshtml
  Codigo/Core/AgendeMeContext.cs
  Codigo/Service/CidadaoService.cs
Labels: 5.0

#347 Implementação da tela 01_03
  Codigo/AgendeMeWeb/Views/Cidadao/Edit.cshtml
Labels: code, 5.0

#350 Implementação da classe de teste do caso de uso Manter Cidadão
  Codigo/ServiceTests/CidadaoServiceTests.cs
Labels: test module, 5.0

#353 Correção do banco referente ao tipo cidadão
  AnaliseProjeto/AgendeMe.mwb
  AnaliseProjeto/AgendeMe.mwb.bak
  Codigo/Core/AgendeMeContext.cs
Labels: bug, 5.0

#358 Dump do banco de dados
  AnaliseProjeto/Dump-AgendeMe.sql
Labels: code, 5.0

#359 Criado Tela_07_01
  Codigo/AgendeMeWeb/Controllers/AgendaDoServicoController.cs
  Codigo/AgendeMeWeb/Models/AgendaDoServicoViewModel.cs
  Codigo/AgendeMeWeb/Views/AgendaDoServico/Index.cshtml
  Codigo/AgendeMeWeb/Views/Shared/_Layout.cshtml
  Codigo/AgendeMeWeb/libman.json
  Codigo/AgendeMeWeb/wwwroot/css/agendaDoServico.css
  Codigo/AgendeMeWeb/wwwroot/lib/datatable.net/css/jquery.dataTables.min.css
  Codigo/AgendeMeWeb/wwwroot/lib/datatable.net/js/jquery.dataTables.min.js
  Codigo/AgendeMeWeb/wwwroot/lib/datatable.net/js/pt-BR.json
  Codigo/Core/DTO/AgendadoservicoDTO.cs
  Codigo/Core/DTO/DatatableDTO.cs
  Codigo/Core/Service/IAgendaDoServicoService.cs
  Codigo/Service/AgendaDoServicoService.cs
  Codigo/Service/Service.csproj
Labels: code, 5.0
