Repository marcosdosea/AgendeMe, pull requests merged in 2022-10, with the labels that each got.

#274 Adicionado pacote Code Generation Design
  Codigo/AgendeMeWeb/AgendeMeWeb.csproj
Labels: bug, repair, 3.0, code

#273 Os atributos de validação foram adicionados. Done #262
  Codigo/AgendeMeWeb/Models/AgendarServicoViewModel.cs
Labels: 3.0, code

#275 Implementado caso de uso Agendar Retorno
  Codigo/AgendeMeWeb/Controllers/AgendarServicoController.cs
  Codigo/AgendeMeWeb/Views/AgendarServico/AgendarRetorno.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Index.cshtml
  Codigo/Service/AgendamentoService.cs
Labels: 3.0, code

#278 Mundanças no arquivo AgendarServicoViewModel.cs
  Codigo/AgendeMeWeb/Models/AgendarServicoViewModel.cs
Labels: 3.0, code

#279 Implementação do caso de uso Manter Órgão Público
  Codigo/AgendeMeWeb/Controllers/OrgaoPublicoController.cs
  Codigo/AgendeMeWeb/Mappers/OrgaoPublicoProfile.cs
  Codigo/AgendeMeWeb/Models/OrgaoPublicoViewModel.cs
  Codigo/AgendeMeWeb/Program.cs
  Codigo/AgendeMeWeb/Views/OrgaoPublico/Create.cshtml
  Codigo/AgendeMeWeb/Views/OrgaoPublico/Delete.cshtml
  Codigo/AgendeMeWeb/Views/OrgaoPublico/Details.cshtml
  Codigo/AgendeMeWeb/Views/OrgaoPublico/Edit.cshtml
  Codigo/AgendeMeWeb/Views/OrgaoPublico/Index.cshtml
  Codigo/Core/Service/IOrgaoPublicoService.cs
  Codigo/Service/OrgaoPublicoService.cs
Labels: 3.0, code

#280 Alteradas palavras do inglês para português. done #277
  Codigo/AgendeMeWeb/Views/AgendaDoServico/Create.cshtml
  Codigo/AgendeMeWeb/Views/AgendaDoServico/Delete.cshtml
  Codigo/AgendeMeWeb/Views/AgendaDoServico/Details.cshtml
  Codigo/AgendeMeWeb/Views/AgendaDoServico/Edit.cshtml
  Codigo/AgendeMeWeb/Views/AgendaDoServico/Index.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/AgendarRetorno.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/AtenderCidadao.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Create.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Delete.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Details.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Edit.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Index.cshtml
  Codigo/AgendeMeWeb/Views/AreaDeServico/Create.cshtml
  Codigo/AgendeMeWeb/Views/AreaDeServico/Delete.cshtml
  Codigo/AgendeMeWeb/Views/AreaDeServico/Details.cshtml
  Codigo/AgendeMeWeb/Views/AreaDeServico/Edit.cshtml
  Codigo/AgendeMeWeb/Views/AreaDeServico/Index.cshtml
  Codigo/AgendeMeWeb/Views/Cargo/Create.cshtml
  Codigo/AgendeMeWeb/Views/Cargo/Delete.cshtml
  Codigo/AgendeMeWeb/Views/Cargo/Details.cshtml
  Codigo/AgendeMeWeb/Views/Cargo/Edit.cshtml
  Codigo/AgendeMeWeb/Views/Cargo/Index.cshtml
  Codigo/AgendeMeWeb/Views/Cidadao/Create.cshtml
  Codigo/AgendeMeWeb/Views/Cidadao/Delete.cshtml
  Codigo/AgendeMeWeb/Views/Cidadao/Details.cshtml
  Codigo/AgendeMeWeb/Views/Cidadao/Edit.cshtml
  Codigo/AgendeMeWeb/Views/Cidadao/Index.cshtml
  Codigo/AgendeMeWeb/Views/Prefeitura/Create.cshtml
  Codigo/AgendeMeWeb/Views/Prefeitura/Delete.cshtml
  Codigo/AgendeMeWeb/Views/Prefeitura/Details.cshtml
  Codigo/AgendeMeWeb/Views/Prefeitura/Edit.cshtml
  Codigo/AgendeMeWeb/Views/Prefeitura/Index.cshtml
  Codigo/AgendeMeWeb/Views/ServicoPublico/Create.cshtml
  Codigo/AgendeMeWeb/Views/ServicoPublico/Delete.cshtml
  Codigo/AgendeMeWeb/Views/ServicoPublico/Details.cshtml
  Codigo/AgendeMeWeb/Views/ServicoPublico/Edit.cshtml
  Codigo/AgendeMeWeb/Views/ServicoPublico/Index.cshtml
Labels: 3.0, code

#281 Implementado tela 03_01
  Codigo/AgendeMeWeb/Controllers/AgendarServicoController.cs
  Codigo/AgendeMeWeb/Program.cs
  Codigo/AgendeMeWeb/Views/AgendarServico/AgendarRetorno.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/AtenderCidadao.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Create.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Delete.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Details.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Edit.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Index.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/List.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/_AjaxAreasDeServico.cshtml
  Codigo/AgendeMeWeb/Views/Shared/_Layout.cshtml
  Codigo/AgendeMeWeb/wwwroot/css/agendeme.css
  Codigo/AgendeMeWeb/wwwroot/js/agendar-servico.js
  Codigo/AgendeMeWeb/wwwroot/js/core-init.js
  Codigo/Core/Service/IAreaDeServicoService.cs
  Codigo/Service/AreaDeServicoService.cs
Labels: code, 4.0

#282 Criado Readme do projeto
  README.md
Labels: 4.0

#294 Criação do projeto "ServiceTests" e das classes de testes do Service
  Codigo/AgendeMe.sln
  Codigo/ServiceTests/AgendaDoServicoServiceTests.cs
  Codigo/ServiceTests/AgendamentoServiceTests.cs
  Codigo/ServiceTests/AreaDeServicoServiceTests.cs
  Codigo/ServiceTests/CargoServiceTests.cs
  Codigo/ServiceTests/CidadaoServiceTests.cs
  Codigo/ServiceTests/OrgaoPublicoServiceTests.cs
  Codigo/ServiceTests/PrefeituraServiceTests.cs
  Codigo/ServiceTests/ServiceTests.csproj
  Codigo/ServiceTests/ServicoPublicoServiceTests.cs
Labels: 4.0, test module

#295 Implementado tela 03_02
  Codigo/AgendeMeWeb/Controllers/AgendarServicoController.cs
  Codigo/AgendeMeWeb/Views/AgendarServico/Index.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/_AjaxAreasDeServico.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/_AjaxServicoPublico.cshtml
  Codigo/AgendeMeWeb/wwwroot/css/agendeme.css
  Codigo/AgendeMeWeb/wwwroot/js/agendar-servico.js
  Codigo/Core/Service/IServicoPublicoService.cs
  Codigo/Service/ServicoPublicoService.cs
Labels: code, 4.0

#296 Adicionado dependência ao Moq e implementado testes da AreaDeServicoController
  Codigo/AgendeMeWebTests/AgendeMeWebTests.csproj
  Codigo/AgendeMeWebTests/Controllers/AreaDeServicoControllerTests.cs
Labels: 4.0, test module

#300 Implementado tela 03_03
  Codigo/AgendeMeWeb/Controllers/AgendarServicoController.cs
  Codigo/AgendeMeWeb/Models/OrgaoPublicoViewModel.cs
  Codigo/AgendeMeWeb/Views/AgendarServico/AreasDeServico.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Index.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/OrgaosPublicos.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/ServicosPublicos.cshtml
  Codigo/AgendeMeWeb/wwwroot/css/agendeme.css
  Codigo/AgendeMeWeb/wwwroot/js/agendar-servico.js
  Codigo/Core/Service/IAreaDeServicoService.cs
  Codigo/Core/Service/IOrgaoPublicoService.cs
  Codigo/Service/AreaDeServicoService.cs
  Codigo/Service/OrgaoPublicoService.cs
  Codigo/Service/ServicoPublicoService.cs
Labels: code, 4.0

#302 Implementado testes para a classe PrefeituraController
  Codigo/AgendeMeWeb/Controllers/PrefeituraController.cs
  Codigo/AgendeMeWebTests/Controllers/PrefeituraControllerTests.cs
Labels: 4.0, test module

#303 Caso de uso Manter Profissional
  Codigo/AgendeMeWeb/Controllers/ProfissionalController.cs
  Codigo/AgendeMeWeb/Mappers/ProfissionalProfile.cs
  Codigo/AgendeMeWeb/Models/ProfissionalViewModel.cs
  Codigo/AgendeMeWeb/Views/Profissional/AddProfissional.cshtml
  Codigo/AgendeMeWeb/Views/Profissional/Delete.cshtml
  Codigo/AgendeMeWeb/Views/Profissional/Details.cshtml
  Codigo/AgendeMeWeb/Views/Profissional/Index.cshtml
  Codigo/Core/DTO/ProfissionalDTO.cs
  Codigo/Core/Service/ICidadaoService.cs
  Codigo/Service/CidadaoService.cs
Labels: code, 4.0

#306 Criado método para pegar todos os cargos de um profissional.
  Codigo/Core/Service/ICargoService.cs
  Codigo/Service/CargoService.cs
Labels: code, 4.0

#307 Criado método para pegar prefeituras em que um profissional trabalha
  Codigo/Core/Service/IPrefeituraService.cs
  Codigo/Service/PrefeituraService.cs
Labels: code, 4.0

#309 Classe OrgaoPublicoControllerTests
  Codigo/AgendeMeWeb/Controllers/OrgaoPublicoController.cs
  Codigo/AgendeMeWebTests/Controllers/OrgaoPublicoControllerTests.cs
Labels: 4.0, test module

#310 Testes criados para CargoController
  Codigo/AgendeMeWebTests/Controllers/CargoControllerTests.cs
Labels: 4.0, test module

#321 Implementado testes para service de cargo.
  Codigo/ServiceTests/CargoServiceTests.cs
Labels: 4.0, test module

#320 Implementação dos métodos de teste referentes a classe AreaDeServicoServiceTests
  Codigo/Service/AreaDeServicoService.cs
  Codigo/ServiceTests/AreaDeServicoServiceTests.cs
Labels: 4.0, test module

#322 Implementar Telas 03_04, 03_05 do caso de uso Agendar Serviço
  Codigo/AgendeMeWeb/Controllers/AgendarServicoController.cs
  Codigo/AgendeMeWeb/Views/AgendarServico/AgendasDoServicoDias.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/AgendasDoServicoHoras.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/AreasDeServico.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/OrgaosPublicos.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/ServicosPublicos.cshtml
  Codigo/AgendeMeWeb/wwwroot/css/agendeme.css
  Codigo/AgendeMeWeb/wwwroot/js/agendar-servico.js
  Codigo/Core/DTO/AgendaDoServicoDiasDTO.cs
  Codigo/Core/DTO/AgendaDoServicoHorasDTO.cs
  Codigo/Core/DTO/OrgaoPublicoDTO.cs
  Codigo/Core/DTO/ServicoPublicoDTO.cs
  Codigo/Core/Service/IAgendaDoServicoService.cs
  Codigo/Core/Service/IOrgaoPublicoService.cs
  Codigo/Core/Service/IServicoPublicoService.cs
  Codigo/Service/AgendaDoServicoService.cs
  Codigo/Service/OrgaoPublicoService.cs
  Codigo/Service/ServicoPublicoService.cs
Labels: code, 4.0

#324 Atualizado relacionamento entre cargos, profissional, prefeitura
  AnaliseProjeto/AgendeMe.mwb
Labels: repair, 4.0

#327 Telas e Mudanças no banco de dados
  AnaliseProjeto/AgendeMe.mwb
  AnaliseProjeto/AgendeMe.mwb.bak
  Codigo/AgendeMeWeb/Controllers/DiaAgendamentoController.cs
  Codigo/AgendeMeWeb/Mappers/DiaAgendamentoProfile.cs
  Codigo/AgendeMeWeb/Models/AgendarServicoViewModel.cs
  Codigo/AgendeMeWeb/Models/DiaAgendamentoViewModel.cs
  Codigo/AgendeMeWeb/Program.cs
  Codigo/AgendeMeWeb/Views/AgendarServico/AgendarRetorno.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/AtenderCidadao.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Create.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Delete.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Details.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Edit.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/List.cshtml
  Codigo/AgendeMeWeb/Views/DiaAgendamento/Create.cshtml
  Codigo/AgendeMeWeb/Views/DiaAgendamento/Delete.cshtml
  Codigo/AgendeMeWeb/Views/DiaAgendamento/Details.cshtml
  Codigo/AgendeMeWeb/Views/DiaAgendamento/Edit.cshtml
  Codigo/AgendeMeWeb/Views/DiaAgendamento/Index.cshtml
  Codigo/Core/Agendamento.cs
  Codigo/Core/AgendeMeContext.cs
  Codigo/Core/Cargo.cs
  Codigo/Core/Cargoprofissionalprefeitura.cs
  Codigo/Core/Cidadao.cs
  Codigo/Core/Diaagendamento.cs
  Codigo/Core/Prefeitura.cs
  Codigo/Core/Service/IDiaAgendamentoService.cs
  Codigo/Core/Servicopublico.cs
  Codigo/Service/CargoService.cs
  Codigo/Service/CidadaoService.cs
  Codigo/Service/DiaAgendamentoService.cs
  Codigo/Service/PrefeituraService.cs
Labels: enhancement, 4.0

#326 Implementado testes para service de prefeitura
  Codigo/ServiceTests/PrefeituraServiceTests.cs
Labels: 4.0, test module

#328 Implementação da tela 01_01 do caso de uso "Manter Cidadão"
  Codigo/AgendeMeWeb/Controllers/CidadaoController.cs
  Codigo/AgendeMeWeb/Views/Cidadao/Details.cshtml
  Codigo/Core/DTO/CidadaoDTO.cs
  Codigo/Core/Service/ICidadaoService.cs
  Codigo/Service/CidadaoService.cs
Labels: code, 4.0

#334 Finalizado caso de uso Manter Profissional.
  Codigo/AgendeMeWeb/Controllers/ProfissionalController.cs
  Codigo/AgendeMeWeb/Mappers/CargoprofissionalprefeituraProfile.cs
  Codigo/AgendeMeWeb/Mappers/ProfissionalProfile.cs
  Codigo/AgendeMeWeb/Models/ProfissionalViewModel.cs
  Codigo/AgendeMeWeb/Views/Profissional/AddProfissional.cshtml
  Codigo/AgendeMeWeb/Views/Profissional/Delete.cshtml
  Codigo/AgendeMeWeb/Views/Profissional/Details.cshtml
  Codigo/AgendeMeWeb/Views/Profissional/Edit.cshtml
  Codigo/AgendeMeWeb/Views/Profissional/Index.cshtml
  Codigo/Core/DTO/ProfissionalDTO.cs
  Codigo/Core/Service/ICidadaoService.cs
  Codigo/Service/CidadaoService.cs
Labels: code, 5.0
