Repository marcosdosea/AgendeMe, pull requests merged in 2022-09, with the labels that each got.

#96 Adicionado campo "Cargo" na tela "Editar Profissional" #91
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_02.jpg
Labels: documentation

#97 Adicionado campo de "Cargo" na tela de cadastro de profissional.
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_01.jpg
Labels: documentation

#90 Criação da pasta "Casos de uso detalhados" e o preenchimento da mesma…
  Requisitos/Casos de uso detalhados/CSU01 - Manter Cidadão.docx
  Requisitos/Casos de uso detalhados/CSU02_ Agendar Retorno.docx
  Requisitos/Casos de uso detalhados/CSU03 - Manter Agendamento.docx
  Requisitos/Casos de uso detalhados/CSU04 - Manter Órgão Público.docx
  Requisitos/Casos de uso detalhados/CSU05 - Manter Serviço Público.docx
  Requisitos/Casos de uso detalhados/CSU06 - Autenticar Usuário.docx
  Requisitos/Casos de uso detalhados/CSU07 - Manter Agenda de Serviços.docx
  Requisitos/Casos de uso detalhados/CSU08 - Manter Prefeitura.docx
  Requisitos/Casos de uso detalhados/CSU09-Manter Área de Serviço.docx
  Requisitos/Casos de uso detalhados/CSU10 - Atender Cidadão.docx
Labels: documentation

#100 Os requisitos funcionais (Alterar e consultar Profissional) foram adi…
  Requisitos/Casos de Uso e Requisitos.pdf
Labels: documentation

#104 O documento "Casos de Uso e Requisitos.pdf" foi substituído pelo docu…
  Requisitos/Casos de Uso e Requisitos.docx
Labels: documentation

#107 Adicionada tela de cadastro de cargo
  Requisitos/Prototipos de Alta Fidelidade/Tela_12_01.jpg
Labels: documentation

#115 Adicionada tela para remoção de cargo.
  Requisitos/Prototipos de Alta Fidelidade/Tela_12_04.jpg
Labels: documentation

#109 Adicionada tela de editar cargo
  Requisitos/Prototipos de Alta Fidelidade/Tela_12_02.jpg
Labels: documentation

#111 Adicionada tela de controle de cargos
  Requisitos/Prototipos de Alta Fidelidade/Tela_12_03.jpg
Labels: documentation

#113 Adicionadas todas as telas com notificações de sucesso.
  Requisitos/Prototipos de Alta Fidelidade/Tela_12_05.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_12_06.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_12_07.jpg
Labels: documentation

#123 O arquivo foi deletado. Done #122
  Requisitos/Casos de Uso e Requisitos.pdf
Labels: documentation

#126 Criada tela de controle para profissionais
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_03.jpg
Labels: documentation

#128 Tela_12_04 com mensagem consertada. fixed #127
  Requisitos/Prototipos de Alta Fidelidade/Tela_12_04.jpg
Labels: documentation

#132 Modelo de banco atualizado
  AnaliseProjeto/AgendeMe.mwb
  AnaliseProjeto/AgendeMe.mwb.bak
Labels: documentation

#135 Atualização do documento "Casos de Uso e Requisitos.docx", no qual fo…
  Requisitos/Casos de Uso e Requisitos.docx
Labels: documentation

#134 Adicionadas telas com notificações de sucesso
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_04.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_06.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_07.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_08.jpg
Labels: documentation

#138 modificadas Tela_02_01 e Tela_02_05.
  Requisitos/Prototipos de Alta Fidelidade/Tela_02_01.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_02_05.jpg
Labels: documentation

#145 Criada tela para apresentar erro ao remover serviço público
  Requisitos/Prototipos de Alta Fidelidade/Tela_05_08.jpg
Labels: documentation

#140 Removidos elemento "especialidade" de todas as telas que o possuíam
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_01.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_02.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_04.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_05.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_06.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_07.jpg
  Requisitos/Prototipos de Alta Fidelidade/Tela_11_08.jpg
Labels: documentation

#156 Tanto os arquivos com o detalhamento dos casos de uso quanto o arquiv…
  Requisitos/Casos de Uso e Requisitos.docx
  Requisitos/Casos de uso detalhados/CSU03 - Agendar Serviço.docx
  Requisitos/Casos de uso detalhados/CSU03 - Manter Agendamento.docx
Labels: documentation

#152 Adição do caso de uso detalhado Manter Profissional na pasta "Casos d…
  Requisitos/Casos de uso detalhados/CSU11-Manter Profissional.docx
Labels: documentation

#191 "Documento de Arquitetura.doc" adicionado com sucesso. Done #175
  AnaliseProjeto/Documento de Arquitetura.doc
Labels: documentation, 2.0

#212 Criação do documento de Guia de Análise e Projeto
  AnaliseProjeto/Guia de Análise e Projeto.docx
Labels: documentation, 2.0

#222 Revisar o documento de arquitetura
  AnaliseProjeto/Documento de Arquitetura.doc
  AnaliseProjeto/Documento de Arquitetura.docx
Labels: documentation, 2.0

#229 Adicionado projeto Core e primeiros arquivos Core
  Codigo/AgendeMe.sln
  Codigo/AgendeMeWeb/appsettings.json
  Codigo/Core/Agendadoservico.cs
  Codigo/Core/Agendamento.cs
  Codigo/Core/AgendeMeContext.cs
  Codigo/Core/Areadeservico.cs
  Codigo/Core/Atendenteorgaopublico.cs
  Codigo/Core/Cargo.cs
  Codigo/Core/Cidadao.cs
  Codigo/Core/Core.csproj
  Codigo/Core/Orgaopublico.cs
  Codigo/Core/Prefeitura.cs
  Codigo/Core/Profissionalcargo.cs
  Codigo/Core/Profissionalprefeitura.cs
  Codigo/Core/Service/IAgendaDoServicoService.cs
  Codigo/Core/Service/IAgendamentoService.cs
  Codigo/Core/Service/IAreaDeServicoService.cs
  Codigo/Core/Service/ICargoService.cs
  Codigo/Core/Service/ICidadaoService.cs
  Codigo/Core/Service/IOrgaoPublicoService.cs
  Codigo/Core/Service/IPrefeituraService.cs
  Codigo/Core/Service/IServicoPublicoService.cs
  Codigo/Core/Servicopublico.cs
Labels: 3.0

#232 Adicionado AutoMapper ao conjunto de depedencias do AgendeMeWeb
  Codigo/AgendeMeWeb/AgendeMeWeb.csproj
Labels: 3.0, code

#244 Adição da conexão com os services e o banco de dados
  Codigo/AgendeMeWeb/Program.cs
Labels: 3.0, code

#246 Mudanças no modelo de banco de dados #245
  AnaliseProjeto/AgendeMe.mwb
  AnaliseProjeto/AgendeMe.mwb.bak
Labels: 3.0

#249 Remoção dos defaults referentes aos ids das tabelas
  AnaliseProjeto/AgendeMe.mwb
Labels: documentation, 3.0

#250 Alterado tipo do atributo "telefone" da tabela cidadão. done #247
  AnaliseProjeto/AgendeMe.mwb
  AnaliseProjeto/AgendeMe.mwb.bak
Labels: documentation, 3.0

#251 Implementado caso de uso (03)AgendarServico
  Codigo/AgendeMeWeb/Controllers/AgendarServicoController.cs
  Codigo/AgendeMeWeb/Mappers/AgendarServicoProfile.cs
  Codigo/AgendeMeWeb/Models/AgendarServicoViewModel.cs
  Codigo/AgendeMeWeb/Program.cs
  Codigo/AgendeMeWeb/Views/AgendarServico/Create.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Delete.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Details.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Edit.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Index.cshtml
  Codigo/Core/AgendeMeContext.cs
  Codigo/Core/Cidadao.cs
  Codigo/Core/Service/IAgendamentoService.cs
  Codigo/Service/AgendamentoService.cs
Labels: 3.0, code

#264 Adição do projeto Util e suas classes com métodos de validação
  Codigo/AgendeMe.sln
  Codigo/Util/CPFAttribute.cs
  Codigo/Util/CepAttribute.cs
  Codigo/Util/Methods.cs
  Codigo/Util/TelefoneCelularAttribute.cs
  Codigo/Util/TelefoneFixoAttribute.cs
  Codigo/Util/Util.csproj
Labels: 3.0, code

#265 MVC do caso de uso (10)Atender Cidadão. done #242
  Codigo/AgendeMeWeb/Controllers/AgendarServicoController.cs
  Codigo/AgendeMeWeb/Views/AgendarServico/AtenderCidadao.cshtml
  Codigo/AgendeMeWeb/Views/AgendarServico/Index.cshtml
Labels: 3.0, code

#266 Implementado caso de uso Manter Área de Serviço
  Codigo/AgendeMeWeb/Controllers/AreaDeServicoController.cs
  Codigo/AgendeMeWeb/Mappers/AreaDeServicoProfile.cs
  Codigo/AgendeMeWeb/Models/AreaDeServicoViewModel.cs
  Codigo/AgendeMeWeb/Program.cs
  Codigo/AgendeMeWeb/Views/AreaDeServico/Create.cshtml
  Codigo/AgendeMeWeb/Views/AreaDeServico/Delete.cshtml
  Codigo/AgendeMeWeb/Views/AreaDeServico/Details.cshtml
  Codigo/AgendeMeWeb/Views/AreaDeServico/Edit.cshtml
  Codigo/AgendeMeWeb/Views/AreaDeServico/Index.cshtml
  Codigo/Core/Service/IAreaDeServicoService.cs
  Codigo/Service/AreaDeServicoService.cs
Labels: 3.0, code

#268 Implementação do caso de uso Manter Cidadão
  Codigo/AgendeMeWeb/Controllers/CidadaoController.cs
  Codigo/AgendeMeWeb/Mappers/CidadaoProfile.cs
  Codigo/AgendeMeWeb/Models/CidadaoViewModel.cs
  Codigo/AgendeMeWeb/Program.cs
  Codigo/AgendeMeWeb/Views/Cidadao/Create.cshtml
  Codigo/AgendeMeWeb/Views/Cidadao/Delete.cshtml
  Codigo/AgendeMeWeb/Views/Cidadao/Details.cshtml
  Codigo/AgendeMeWeb/Views/Cidadao/Edit.cshtml
  Codigo/AgendeMeWeb/Views/Cidadao/Index.cshtml
  Codigo/Core/Service/ICidadaoService.cs
  Codigo/Service/CidadaoService.cs
Labels: 3.0, code

#267 Implementação do caso de uso de Manter Prefeitura
  Codigo/AgendeMeWeb/Controllers/PrefeituraController.cs
  Codigo/AgendeMeWeb/Mappers/PrefeituraProfile.cs
  Codigo/AgendeMeWeb/Models/PrefeituraViewModel.cs
  Codigo/AgendeMeWeb/Program.cs
  Codigo/AgendeMeWeb/Views/Prefeitura/Create.cshtml
  Codigo/AgendeMeWeb/Views/Prefeitura/Delete.cshtml
  Codigo/AgendeMeWeb/Views/Prefeitura/Details.cshtml
  Codigo/AgendeMeWeb/Views/Prefeitura/Edit.cshtml
  Codigo/AgendeMeWeb/Views/Prefeitura/Index.cshtml
  Codigo/Core/Service/IPrefeituraService.cs
  Codigo/Service/PrefeituraService.cs
Labels: 3.0, code

#269 Implementado caso de uso Manter Cargo.
  Codigo/AgendeMeWeb/Controllers/CargoController.cs
  Codigo/AgendeMeWeb/Mappers/CargoProfile.cs
  Codigo/AgendeMeWeb/Models/CargoViewModel.cs
  Codigo/AgendeMeWeb/Program.cs
  Codigo/AgendeMeWeb/Views/Cargo/Create.cshtml
  Codigo/AgendeMeWeb/Views/Cargo/Delete.cshtml
  Codigo/AgendeMeWeb/Views/Cargo/Details.cshtml
  Codigo/AgendeMeWeb/Views/Cargo/Edit.cshtml
  Codigo/AgendeMeWeb/Views/Cargo/Index.cshtml
  Codigo/AgendeMeWeb/Views/Prefeitura/Details.cshtml
  Codigo/Core/Service/ICargoService.cs
  Codigo/Service/CargoService.cs
Labels: 3.0, code

#270 Implementado caso de uso 05 Manter Serviço Publico
  Codigo/AgendeMeWeb/Controllers/ServicoPublicoController.cs
  Codigo/AgendeMeWeb/Mappers/ServicoPublicoProfile.cs
  Codigo/AgendeMeWeb/Models/ServicoPublicoViewModel.cs
  Codigo/AgendeMeWeb/Program.cs
  Codigo/AgendeMeWeb/Views/ServicoPublico/Create.cshtml
  Codigo/AgendeMeWeb/Views/ServicoPublico/Delete.cshtml
  Codigo/AgendeMeWeb/Views/ServicoPublico/Details.cshtml
  Codigo/AgendeMeWeb/Views/ServicoPublico/Edit.cshtml
  Codigo/AgendeMeWeb/Views/ServicoPublico/Index.cshtml
  Codigo/Core/Service/IServicoPublicoService.cs
  Codigo/Service/ServicoPublicoService.cs
Labels: 3.0, code

#271 Branch gabriel245 - Implementando o caso de uso Manter Agenda do Servico
  Codigo/AgendeMeWeb/Controllers/AgendaDoServicoController.cs
  Codigo/AgendeMeWeb/Mappers/AgendaDoServicoProfile.cs
  Codigo/AgendeMeWeb/Models/AgendaDoServicoViewModel.cs
  Codigo/AgendeMeWeb/Program.cs
  Codigo/AgendeMeWeb/Views/AgendaDoServico/Create.cshtml
  Codigo/AgendeMeWeb/Views/AgendaDoServico/Delete.cshtml
  Codigo/AgendeMeWeb/Views/AgendaDoServico/Details.cshtml
  Codigo/AgendeMeWeb/Views/AgendaDoServico/Edit.cshtml
  Codigo/AgendeMeWeb/Views/AgendaDoServico/Index.cshtml
  Codigo/Core/Service/IAgendaDoServicoService.cs
  Codigo/Service/AgendaDoServicoService.cs
Labels: 3.0, code
